# -------- Stage 1: Build --------
FROM node:20-alpine AS build

WORKDIR /app

# Copiar package.json primero (mejor cache)
COPY frontend/package*.json ./
RUN npm install

# Copiar código
COPY frontend/ .

# Build producción
RUN npm run build


# -------- Stage 2: Nginx --------
FROM nginx:stable-alpine

# Copiar config personalizada
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar build
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]