"""add_status_to_expense

Revision ID: 195a8571f735
Revises: e446e312f860
Create Date: 2026-03-11 01:19:22.153879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195a8571f735'
down_revision = 'e446e312f860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'status')
    # ### end Alembic commands ###
