"""Add is_credit_card to Account model

Revision ID: 222532e29d73
Revises: a5ccafde9c4c
Create Date: 2026-02-12 08:09:56.828907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222532e29d73'
down_revision = 'a5ccafde9c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_credit_card', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_credit_card')
    # ### end Alembic commands ###
