"""Add new models and update expense

Revision ID: 9d29a798aed5
Revises: 4efb414dde6e
Create Date: 2026-02-12 02:04:04.075201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d29a798aed5'
down_revision = '4efb414dde6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipients_id'), 'recipients', ['id'], unique=False)
    op.create_index(op.f('ix_recipients_name'), 'recipients', ['name'], unique=False)

    # Add movement_type column as nullable first
    op.add_column('expenses', sa.Column('movement_type', sa.String(), nullable=True))
    # Update existing rows with a default value
    op.execute("UPDATE expenses SET movement_type = 'expense' WHERE movement_type IS NULL")
    # Alter column to be non-nullable
    op.alter_column('expenses', 'movement_type', existing_type=sa.String(), nullable=False)

    op.add_column('expenses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('is_installment', sa.Boolean(), nullable=True))
    op.add_column('expenses', sa.Column('num_installments', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('installment_amount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'recipients', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'installment_amount')
    op.drop_column('expenses', 'num_installments')
    op.drop_column('expenses', 'is_installment')
    op.drop_column('expenses', 'recipient_id')
    op.drop_column('expenses', 'account_id')
    op.drop_column('expenses', 'category_id')
    op.drop_column('expenses', 'movement_type')
    op.drop_index(op.f('ix_recipients_name'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_id'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
