"""Add application_date to Expense model

Revision ID: a5ccafde9c4c
Revises: 9d29a798aed5
Create Date: 2026-02-12 01:35:26.814103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ccafde9c4c'
down_revision = '9d29a798aed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add application_date column as nullable=True first
    op.add_column('expenses', sa.Column('application_date', sa.Date(), nullable=True))

    # 2. Update existing rows: Set application_date to the value of the 'date' column
    #    For existing expenses, the application date is assumed to be the expense date.
    op.execute("UPDATE expenses SET application_date = date")

    # 3. Alter the application_date column to be nullable=False
    op.alter_column('expenses', 'application_date',
               existing_type=sa.Date(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'application_date')
    # ### end Alembic commands ###
